### PR TITLE
BEAST: automatically create and connect new bus for new tracks

### LINKED ISSUE #10: Mixer assignment broken
Usually when composing, I want every track on its own mixer channel. There used to be a script (Song -> Assign Tracks to individual Mixer Busses), which is more of a workaround solution. But the script is currently broken. I have no problem with reimplementing the script in Python or whatever language.

Or BEAST could just automatically use one mixer bus per created track. Or it could ask when creating a track: should I create a mixer bus for this track, too. Other DAWs do one of these two options. It could also ask for an instrument to assign to the newly created track. That way track creation would setup the mixer AND set an instrument.

In any case, this is somewhat annoying and could be improved....

### PR DESCRIPTION
**Pull request by swesterfeld**
Fixes https://github.com/tim-janik/beast/issues/10

Signed-off-by: Stefan Westerfeld <stefan@space.twc.de>

### CODE REVIEW

**Comment by tim-janik** [comment]
Great, thanks for that work. A few nitpicks, would be nice if you can change the pull request to cater:
git log messages, please use the prefix "BST:" for the beast-gkt dir (and "GXK:" for beast-gtk/gxk). These are originating in the namespace prefix used in those directories.
+      SfiSeq *seq;
+      bse_proxy_get (track.proxy_id(), "outputs", &seq, NULL);
Please per default initialize output variables like "SfiSeq *seq = NULL;", so if we have a bug somewhere, we are more likely to get a NULL pointer crash, rather than random behavior. And about this logic:
+          // automatically remove output bus if
+          //  - we have only one output bus
+          //  - this bus doesn't have any other inputs
Shouldn't we remove all output busses, as long as the track to be deleted is the only input?
That way, no matter what kind of routing is setup, if a user deletes all tracks one by one, there won't be any busses left at the end except for the master bus (assuming the user didn't have any orphan busses to start with).
Oh and, did you test that your patches work across undo/redo (unfortunately we can only test this manually atm, though automated undo testing would be great).

**Comment by tim-janik** [comment]
With your PR applied, the following sequence of actions triggers a warning for me:
  start beast -> Project/New-Song -> Add-Track -> Delete-Mixer/Bus-1 -> Undo -> Undo
Yields:
WARNING: error during undo 'connect_bus' of item "BseBus::Master-1": Parent mismatch

**Comment by swesterfeld** [comment]
> Shouldn't we remove all output busses, as long as the track to be deleted is the only input?

I considered this deletion strategy, and what I don't like about it is that it can delete user-created busses (which were not created by BEAST automatically). For an example assume that we had effects in the mixer.

1. The user creates a track: Snare
2. Then he creates an FX bus, with some effects (Reverb)
3. He connects Snare to FX, to get reverb
4. He creates another Track: HiHats
5. He connects HiHats to FX.

So far, we have two track busses and one FX bus in the mixer

If the user now deletes all tracks (with your deletion strategy), the FX bus will be removed, although it was  manually created. With my deletion strategy, no bus will be removed.

Both are probably suboptimal, but I implemented the "safe" version, which will usually not delete busses it didn't create.

**Comment by tim-janik** [comment]
Ok, I see your reasonings.
I still think we should delete unconnected busses though, because:
a) If the user really intended to keep important stuff around in the bus, there's always Undo if needed.
b) To simplify the user interface in the future, we should probably move towards a 1:1 relationship  between tracks and busses, avoiding orphan busses (or tracks) is a good step into that direction.

**Comment by swesterfeld** [comment]
> Ok, I see your reasonings.
> I still think we should delete unconnected busses though, because:
> a) If the user really intended to keep important stuff around in the bus, there's always Undo if needed.
> b) To simplify the user interface in the future, we should probably move towards a 1:1 relationship between tracks and busses, avoiding orphan busses (or tracks) is a good step into that direction.

Ok, I don't have strong feelings toward either deletion strategy, so I changed it.
I also changed
- BEAST -> BST: in commit messages
- nullptr initialization for SfiSeq*

We still have the undo-problem though:

>With your PR applied, the following sequence of actions triggers a warning for me:
start beast -> Project/New-Song -> Add-Track -> Delete-Mixer/Bus-1 -> Undo -> Undo
> Yields:
> WARNING: error during undo 'connect_bus' of item "BseBus::Master-1": Parent mismatch

I can reproduce this, but I have no idea what would be necessary to fix it (mainly because I'm completely clueless about how undo works internally).

**Comment by tim-janik** [comment]
Hi, please rebase and resolve conflicts here.

> I have no idea what would be necessary to fix it (mainly because I'm completely clueless about how undo works internally).

It's really not that hard to use / model. Every editing API call e.g. add-track() pushes a lambda onto the undo stack that does the exact opposite, i.e. add-track will push remove-track(new-track-id). The only tricky bit here is the object references that have to be passed into the lambdas, because they have to be wrapped to stay persistent. You're best off looking at existing code for that.
Once the user triggers undo, we simply pick the last lambda group from the undo stack (group - since multiple undo lambda calls can comprise a single undo step), and execute it. Since the execution will itself be an API call again, we swap redo/undo stacks around the execution which means that lambda{remove-track()} will actually push another add-track() that lands on the redo stack this way.

**Comment by swesterfeld** [comment]
Ok, I rebased the branch (more like: manually fixed/recommitted what we need). As you say, it is possible to trigger an undo problem like this:

> With your PR applied, the following sequence of actions triggers a warning for me:
> start beast -> Project/New-Song -> Add-Track -> Delete-Mixer/Bus-1 -> Undo -> Undo
> Yields:
> WARNING: error during undo 'connect_bus' of item "BseBus::Master-1": Parent mismatch

However, I investigated the issue and it is not a problem created by the commits in this branch. I've created a new issue for this problem https://github.com/tim-janik/beast/issues/79 and this shouldn't block merging this PR.

**Comment by tim-janik** [comment]
Thank you for your efforts.
Beast development is continued in [Anklang](https://github.com/tim-janik/beast/pull/github.com/tim-janik/anklang/).

For the record, Undo recording is easier in Anklang.
Anklang pushes C++ lambdas onto the undo stack  where objects are pointer-referenced and kept alive via std::shared_ptr<>. 
Undo for objects (track, clip, etc) removal isn't implemented yet, but the plan is to allow repeated unparent/reparent states on objects, which will make Undo a lot easier and avoids dangling references automatically.
The reparenting is something that would have been a lot harder to implement for Beast.

**Pull request closed without merging**
